### ISSUE TITLE
Handle missing /var/run/netns

### ISSUE THREAD

**Issue by Coderlane** [whyrusleeping/go-netdef#4]
### Problem
The first time I run `netdef` I get the following output:

```
$ sudo ./netdef create ../example.nd 
open /var/run/netns: no such file or directory
```

### Observations
Sure enough, the directory doesn't exist.
```
$ stat /var/run/netns
stat: cannot stat '/var/run/netns': No such file or directory
```

If I run `ip netns add blah` then `ip netns delete blah`, `netdef` starts to work.

### Proposals

I see two easy was of fixing this:

1) Treat an empty directory as not having any names. (Just handle `ENOENT`)
2) Use `ip netns list` directly and parse the output.

I'm leaning towards the second option, but what would you prefer?

**Comment by whyrusleeping** [comment]
Hem... Either way works. Maybe option 2 is cleaner
